// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeLVEmMTeAS0xgs6y-bMygmJTvoBSdmI8',
    appId: '1:561444116515:web:ba33a94dcba970cd7e7996',
    messagingSenderId: '561444116515',
    projectId: 'blindmate-1fe44',
    authDomain: 'blindmate-1fe44.firebaseapp.com',
    storageBucket: 'blindmate-1fe44.firebasestorage.app',
    measurementId: 'G-E4BM4VVNYE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI4vsjggG4equicgcg0LICNHLhXKRcByw',
    appId: '1:561444116515:android:29c351c01a46a25c7e7996',
    messagingSenderId: '561444116515',
    projectId: 'blindmate-1fe44',
    storageBucket: 'blindmate-1fe44.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs-UjKFEipu41Nmjgt9MbBHHtnmRjWCL4',
    appId: '1:561444116515:ios:18d6a7d053c623947e7996',
    messagingSenderId: '561444116515',
    projectId: 'blindmate-1fe44',
    storageBucket: 'blindmate-1fe44.firebasestorage.app',
    iosBundleId: 'com.example.blindmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs-UjKFEipu41Nmjgt9MbBHHtnmRjWCL4',
    appId: '1:561444116515:ios:18d6a7d053c623947e7996',
    messagingSenderId: '561444116515',
    projectId: 'blindmate-1fe44',
    storageBucket: 'blindmate-1fe44.firebasestorage.app',
    iosBundleId: 'com.example.blindmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeLVEmMTeAS0xgs6y-bMygmJTvoBSdmI8',
    appId: '1:561444116515:web:4d24fdbfc88d01757e7996',
    messagingSenderId: '561444116515',
    projectId: 'blindmate-1fe44',
    authDomain: 'blindmate-1fe44.firebaseapp.com',
    storageBucket: 'blindmate-1fe44.firebasestorage.app',
    measurementId: 'G-6KPYYKC1V8',
  );
}
